<div class="modal fade" id="userModal" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content no 1-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title text-center form-title"><span id="userModalTitle"></span></h4>
        </div>
        <div class="modal-body padtrbl">

          <div class="login-box-body">
            <p class="login-box-msg"><span id="userModalMessage"></span></p>
            <div class="form-group">
              <form name="userManagementForm" id="userManagementForm">
                <div class="form-group has-feedback">
                  <!----- First name -------------->
                  <input class="form-control" placeholder="First Name" id="firstName" type="text" />
                  <span style="display:none;font-weight:bold; position:absolute;color: red;position: absolute;padding:4px;font-size: 11px;background-color:rgba(128, 128, 128, 0.26);z-index: 17;  right: 27px; top: 5px;" id="firstNameFeedback"></span>
                  <!---First Name required ! -->
                  <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                  <!----- Last Name -------------->
                  <input class="form-control" placeholder="Last Name" id="lastName" type="text" />
                  <span style="display:none;font-weight:bold; position:absolute;color: grey;position: absolute;padding:4px;font-size: 11px;background-color:rgba(128, 128, 128, 0.26);z-index: 17;  right: 27px; top: 5px;" id="lastNameFeedback"></span>
                  <!---Last Name required  ! -->
                  <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                  <!----- Last Name -------------->
                  <input class="form-control" placeholder="Email" id="email" type="text" />
                  <span style="display:none;font-weight:bold; position:absolute;color: grey;position: absolute;padding:4px;font-size: 11px;background-color:rgba(128, 128, 128, 0.26);z-index: 17;  right: 27px; top: 5px;" id="emailFeedback"></span>
                  <!---Last Name required  ! -->
                  <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                  <!----- Last Name -------------->
                  <input class="form-control" placeholder="Position" id="position" type="text" />
                  <span style="display:none;font-weight:bold; position:absolute;color: grey;position: absolute;padding:4px;font-size: 11px;background-color:rgba(128, 128, 128, 0.26);z-index: 17;  right: 27px; top: 5px;" id="positionFeedback"></span>
                  <!---Last Name required  ! -->
                  <span class="glyphicon glyphicon-king form-control-feedback"></span>
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    <button type="submit" class="btn btn-green btn-block btn-flat"><span id="userModalBtnCaption"></span></button>
                  </div>
                </div>
                <div class="row margin-top-20">
                  <div class="col-xs-12">
                    <div id="success" class="alert alert-success hid">
                        <p><strong>The form has been submitted successfully</strong></p>
                        <p>
                          First name: <span id="firstNameSubmit"></span><br />
                          Last name: <span id="lastNameSubmit"></span><br />
                          Email: <span id="emailSubmit"></span><br />
                          Position: <span id="positionSubmit"></span><br />
                        </p>
                    </div>
                    <div id="err" class="alert alert-danger hid">
                        <p><strong>Some errors occured</strong></p>
                        <p>
                          First name: <span id="firstNameSubmitErr"></span><br />
                          Last name: <span id="lastNameSubmitErr"></span><br />
                          Email: <span id="emailSubmitErr"></span><br />
                          Position: <span id="positionSubmitErr"></span><br />
                        </p>
                    </div>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
      </div>
</div>