
  <!--Banner-->
  <div class="banner">
    <div class="bg-color">
      <div class="container">
        <div class="row">
          <div class="banner-text text-center">
            <div class="text-border">
              <h2 class="text-dec">User Admin App</h2>
            </div>
            <div class="intro-para text-center quote">
              <p class="big-text">Learning Today . . . Leading Tomorrow.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/ Banner-->
  <!--Feature-->
  <section id="feature" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="header-section text-center">
          <h2>Welcom on the mentor user admin platform</h2>
          <p> With this app you can manage all existing users of the user admin platform. It is also possible to create new ones. This site is still under construction. New features will be added continuously.</p>
          <p>Here under I explain a bit the used technologies</p>
          <hr class="bottom-line">
        </div>
        <div class="feature-info">
          <div class="fea">
            <div class="col-md-4">
              <div class="heading pull-right">
                <h4>Used Technologies</h4>
                <p>As stated in the assessment, I have used php 7.3, Zend Framework 3 and bootstrap 3. For the front-end JQuery has been used. My personal JQuery code can be found in public/js/application.js</p>
              </div>
              <div class="fea-img pull-left">
                <i class="fa fa-css3"></i>
              </div>
            </div>
          </div>
          <div class="fea">
            <div class="col-md-4">
              <div class="heading pull-right">
                <h4>No database - delivered data file</h4>
                <p>If I would use a database, I would choose MySQL, which I am used to manage with MySQL workbench. I have worked with doctrine. Under the src folder in the module, I would foresee an Entity folder, in which a class per table is foresoon so with a get and a set function for each column of the table.</p>
              </div>
              <div class="fea-img pull-left">
                <i class="fa fa-drupal"></i>
              </div>
            </div>
          </div>
          <div class="fea">
            <div class="col-md-4">
              <div class="heading pull-right">
                <h4>MENTOR template</h4>
                <p>Since layout is not a priority of this assessment, I have integrated a free bootstrap 3 template, MENTOR. Under public/css you wil find style.css. At the end of the file you will find a little bit of CSS that I wrote myself, the rest has been delivered by the template.</p>
              </div>
              <div class="fea-img pull-left">
                <i class="fa fa-trophy"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ feature-->
